// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Lifty
//
//  Elevator Control API
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0.0
//  Contact: <nelz@orionlabs.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
