// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Elevator Control API",
    "title": "Lifty",
    "contact": {
      "email": "nelz@orionlabs.io"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/admin/inventory/{pwd}": {
      "get": {
        "description": "Operator Ease-Of-Use: List out Floor and Car identifiers",
        "summary": "List Floor and Car IDs",
        "operationId": "inventory",
        "parameters": [
          {
            "type": "string",
            "description": "The password is ` + "`" + `p4ssw3rd` + "`" + `",
            "name": "pwd",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "count",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "additionalProperties": false
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        }
      }
    },
    "/car/{car_id}/floor/current": {
      "get": {
        "description": "What floor is the car currently on",
        "summary": "Current Floor",
        "operationId": "currentFloor",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the car we are investigating",
            "name": "car_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "floor",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/floor_count": {
      "get": {
        "description": "Total number of stops in this elevator",
        "summary": "Number of stops",
        "operationId": "floorCount",
        "responses": {
          "200": {
            "description": "count",
            "schema": {
              "type": "object",
              "required": [
                "count"
              ],
              "properties": {
                "count": {
                  "type": "integer",
                  "format": "int32"
                }
              },
              "additionalProperties": false
            }
          }
        }
      }
    },
    "/welcome": {
      "get": {
        "description": "Simple welcome message to verify service is up",
        "summary": "welcome",
        "operationId": "welcome",
        "responses": {
          "200": {
            "description": "successful connection",
            "schema": {
              "type": "object",
              "required": [
                "msg"
              ],
              "properties": {
                "msg": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Elevator Control API",
    "title": "Lifty",
    "contact": {
      "email": "nelz@orionlabs.io"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/admin/inventory/{pwd}": {
      "get": {
        "description": "Operator Ease-Of-Use: List out Floor and Car identifiers",
        "summary": "List Floor and Car IDs",
        "operationId": "inventory",
        "parameters": [
          {
            "type": "string",
            "description": "The password is ` + "`" + `p4ssw3rd` + "`" + `",
            "name": "pwd",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "count",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/InventoryOKBodyItems0"
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        }
      }
    },
    "/car/{car_id}/floor/current": {
      "get": {
        "description": "What floor is the car currently on",
        "summary": "Current Floor",
        "operationId": "currentFloor",
        "parameters": [
          {
            "type": "string",
            "description": "The ID of the car we are investigating",
            "name": "car_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "floor",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/floor_count": {
      "get": {
        "description": "Total number of stops in this elevator",
        "summary": "Number of stops",
        "operationId": "floorCount",
        "responses": {
          "200": {
            "description": "count",
            "schema": {
              "type": "object",
              "required": [
                "count"
              ],
              "properties": {
                "count": {
                  "type": "integer",
                  "format": "int32"
                }
              },
              "additionalProperties": false
            }
          }
        }
      }
    },
    "/welcome": {
      "get": {
        "description": "Simple welcome message to verify service is up",
        "summary": "welcome",
        "operationId": "welcome",
        "responses": {
          "200": {
            "description": "successful connection",
            "schema": {
              "type": "object",
              "required": [
                "msg"
              ],
              "properties": {
                "msg": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          }
        }
      }
    }
  },
  "definitions": {
    "InventoryOKBodyItems0": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}`))
}
