// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CurrentFloorHandlerFunc turns a function with the right signature into a current floor handler
type CurrentFloorHandlerFunc func(CurrentFloorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CurrentFloorHandlerFunc) Handle(params CurrentFloorParams) middleware.Responder {
	return fn(params)
}

// CurrentFloorHandler interface for that can handle valid current floor params
type CurrentFloorHandler interface {
	Handle(CurrentFloorParams) middleware.Responder
}

// NewCurrentFloor creates a new http.Handler for the current floor operation
func NewCurrentFloor(ctx *middleware.Context, handler CurrentFloorHandler) *CurrentFloor {
	return &CurrentFloor{Context: ctx, Handler: handler}
}

/* CurrentFloor swagger:route GET /car/{car_id}/floor/current currentFloor

Current Floor

What floor is the car currently on

*/
type CurrentFloor struct {
	Context *middleware.Context
	Handler CurrentFloorHandler
}

func (o *CurrentFloor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCurrentFloorParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CurrentFloorOKBody current floor o k body
//
// swagger:model CurrentFloorOKBody
type CurrentFloorOKBody struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this current floor o k body
func (o *CurrentFloorOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this current floor o k body based on context it is used
func (o *CurrentFloorOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CurrentFloorOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CurrentFloorOKBody) UnmarshalBinary(b []byte) error {
	var res CurrentFloorOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
