// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CurrentFloorOKCode is the HTTP code returned for type CurrentFloorOK
const CurrentFloorOKCode int = 200

/*CurrentFloorOK floor

swagger:response currentFloorOK
*/
type CurrentFloorOK struct {

	/*
	  In: Body
	*/
	Payload *CurrentFloorOKBody `json:"body,omitempty"`
}

// NewCurrentFloorOK creates CurrentFloorOK with default headers values
func NewCurrentFloorOK() *CurrentFloorOK {

	return &CurrentFloorOK{}
}

// WithPayload adds the payload to the current floor o k response
func (o *CurrentFloorOK) WithPayload(payload *CurrentFloorOKBody) *CurrentFloorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the current floor o k response
func (o *CurrentFloorOK) SetPayload(payload *CurrentFloorOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CurrentFloorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CurrentFloorNotFoundCode is the HTTP code returned for type CurrentFloorNotFound
const CurrentFloorNotFoundCode int = 404

/*CurrentFloorNotFound Not Found

swagger:response currentFloorNotFound
*/
type CurrentFloorNotFound struct {
}

// NewCurrentFloorNotFound creates CurrentFloorNotFound with default headers values
func NewCurrentFloorNotFound() *CurrentFloorNotFound {

	return &CurrentFloorNotFound{}
}

// WriteResponse to the client
func (o *CurrentFloorNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
