// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FloorCountHandlerFunc turns a function with the right signature into a floor count handler
type FloorCountHandlerFunc func(FloorCountParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FloorCountHandlerFunc) Handle(params FloorCountParams) middleware.Responder {
	return fn(params)
}

// FloorCountHandler interface for that can handle valid floor count params
type FloorCountHandler interface {
	Handle(FloorCountParams) middleware.Responder
}

// NewFloorCount creates a new http.Handler for the floor count operation
func NewFloorCount(ctx *middleware.Context, handler FloorCountHandler) *FloorCount {
	return &FloorCount{Context: ctx, Handler: handler}
}

/* FloorCount swagger:route GET /floor_count floorCount

Number of stops

Total number of stops in this elevator

*/
type FloorCount struct {
	Context *middleware.Context
	Handler FloorCountHandler
}

func (o *FloorCount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFloorCountParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// FloorCountOKBody floor count o k body
//
// swagger:model FloorCountOKBody
type FloorCountOKBody struct {

	// count
	// Required: true
	Count *int32 `json:"count"`
}

// Validate validates this floor count o k body
func (o *FloorCountOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FloorCountOKBody) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("floorCountOK"+"."+"count", "body", o.Count); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this floor count o k body based on context it is used
func (o *FloorCountOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *FloorCountOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *FloorCountOKBody) UnmarshalBinary(b []byte) error {
	var res FloorCountOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
