// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FloorCountOKCode is the HTTP code returned for type FloorCountOK
const FloorCountOKCode int = 200

/*FloorCountOK count

swagger:response floorCountOK
*/
type FloorCountOK struct {

	/*
	  In: Body
	*/
	Payload *FloorCountOKBody `json:"body,omitempty"`
}

// NewFloorCountOK creates FloorCountOK with default headers values
func NewFloorCountOK() *FloorCountOK {

	return &FloorCountOK{}
}

// WithPayload adds the payload to the floor count o k response
func (o *FloorCountOK) WithPayload(payload *FloorCountOKBody) *FloorCountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the floor count o k response
func (o *FloorCountOK) SetPayload(payload *FloorCountOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FloorCountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
