// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewInventoryParams creates a new InventoryParams object
//
// There are no default values defined in the spec.
func NewInventoryParams() InventoryParams {

	return InventoryParams{}
}

// InventoryParams contains all the bound params for the inventory operation
// typically these are obtained from a http.Request
//
// swagger:parameters inventory
type InventoryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The password is `p4ssw3rd`
	  Required: true
	  In: path
	*/
	Pwd string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewInventoryParams() beforehand.
func (o *InventoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPwd, rhkPwd, _ := route.Params.GetOK("pwd")
	if err := o.bindPwd(rPwd, rhkPwd, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPwd binds and validates parameter Pwd from path.
func (o *InventoryParams) bindPwd(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Pwd = raw

	return nil
}
