// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// WelcomeOKCode is the HTTP code returned for type WelcomeOK
const WelcomeOKCode int = 200

/*WelcomeOK successful connection

swagger:response welcomeOK
*/
type WelcomeOK struct {

	/*
	  In: Body
	*/
	Payload *WelcomeOKBody `json:"body,omitempty"`
}

// NewWelcomeOK creates WelcomeOK with default headers values
func NewWelcomeOK() *WelcomeOK {

	return &WelcomeOK{}
}

// WithPayload adds the payload to the welcome o k response
func (o *WelcomeOK) WithPayload(payload *WelcomeOKBody) *WelcomeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the welcome o k response
func (o *WelcomeOK) SetPayload(payload *WelcomeOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WelcomeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
